// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using targilDotNet;

#nullable disable

namespace targilDotNet.Migrations
{
    [DbContext(typeof(KeyPressContext))]
    [Migration("20220119082723_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("targilDotNet.Key", b =>
                {
                    b.Property<string>("KeyName")
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime>("startTimeastamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("KeyName", "startTimeastamp");

                    b.ToTable("Keys");
                });
#pragma warning restore 612, 618
        }
    }
}
